libdigidocpp: digidoc::X509Cert Class Reference
digidoc::X509Cert Class Reference
Wrapper for OpenSSL X509 certificate structure.
#include <X509Cert.h>
Public Types
enum Format { Der, Pem }
enum KeyUsage {
DigitalSignature = 0, NonRepudiation, KeyEncipherment, DataEncipherment,
KeyAgreement, KeyCertificateSign, CRLSign, EncipherOnly,
DecipherOnly
}
Public Member Functions
X509Cert (X509 *cert=0)
X509Cert (const unsigned char *bytes, size_t size, Format format=Der)
X509Cert (const std::vector< unsigned char > &bytes, Format format=Der)
X509Cert (const std::string &path, Format format=Pem)
X509Cert (X509Cert &&other)
X509Cert (const X509Cert &other)
~X509Cert ()
std::string serial () const
std::string issuerName (const std::string &obj=std::string()) const
std::string subjectName (const std::string &obj=std::string()) const
std::vector< KeyUsage > keyUsage () const
std::vector< std::string > certificatePolicies () const
bool isCA () const
bool isValid (time_t *t=0) const
X509 * handle () const
operator std::vector< unsigned char > () const
X509Cert & operator= (const X509Cert &other)
X509Cert & operator= (X509Cert &&other)
bool operator! () const
bool operator== (const X509Cert &other) const
bool operator!= (const X509Cert &other) const
Detailed Description
Wrapper for OpenSSL X509 certificate structure.
Member Enumeration Documentation
enum digidoc::X509Cert::Format
Binary encoding format
Enumerator
Der
ASN.1 syntax
Pem
Base64 encoded ASN.1 syntax
enum digidoc::X509Cert::KeyUsage
Key usage bits defined in certificate
Enumerator
DigitalSignature
NonRepudiation
Used for signing certificate selection in the current library
KeyEncipherment
DataEncipherment
KeyAgreement
KeyCertificateSign
CRLSign
EncipherOnly
DecipherOnly
Constructor & Destructor Documentation
X509Cert::X509Cert (X509 * cert = 0) explicit
Creates copy of the OpenSSL X509 certificate.
Parameters
cert X509 certificate structure to be wrapped.
X509Cert::X509Cert (const unsigned char * bytes, size_t size, Format format = Der) explicit
Creates X509 certificate from bytes.
Parameters
bytes X509 certificate in bytes.
size of X509 certificate in bytes.
format Format input bytes format
Exceptions
Exception throws exception if X509 certificate parsing failed.
References Der.
X509Cert::X509Cert (const std::vector< unsigned char > & bytes, Format format = Der) explicit
Creates X509 certificate from bytes.
Parameters
bytes X509 certificate in bytes.
format Format input bytes format
Exceptions
Exception throws exception if X509 certificate parsing failed.
X509Cert::X509Cert (const std::string & path, Format format = Pem) explicit
Creates X509 certificate from path.
Parameters
path X509 certificate path.
format Format input bytes format
Exceptions
Exception throws exception if X509 certificate parsing failed.
References Der.
X509Cert::X509Cert (X509Cert && other)
Move constructor.
X509Cert::X509Cert (const X509Cert & other)
Copy constructor.
X509Cert::~X509Cert ()
Clean up underlying X509 data.
Member Function Documentation
vector< string > X509Cert::certificatePolicies () const
Returns current certificate policies
Referenced by digidoc::Signer::method().
X509 * X509Cert::handle () const
Returns certificate internal handle (OpenSSL X509 struct)
bool X509Cert::isCA () const
Rerturns true if certificate is CA
string X509Cert::issuerName (const std::string & obj = std::string()) const
Returns issuer name as string.
Parameters
obj if set to empty string then returns whole issuer name. Otherwise, for example, if set to CN then returns Common name part from issuer name.
Exceptions
Exception exception is throws if the conversion failed.
bool X509Cert::isValid (time_t * t = 0) const
Validates if certificate is in valid time slot
Parameters
t If param is 0 then current time is used, else defined time
vector< X509Cert::KeyUsage > X509Cert::keyUsage () const
Returns current certificate key usage bits
digidoc::X509Cert::operator std::vector< unsigned char > () const
bool X509Cert::operator! () const
Negative operator to check if object is valid
bool X509Cert::operator!= (const X509Cert & other) const
Not equal operator to compare two objects
References operator==().
X509Cert & X509Cert::operator= (const X509Cert & other)
Assign operator to make copy of object
X509Cert & X509Cert::operator= (X509Cert && other)
Assign operator to make copy of object
bool X509Cert::operator== (const X509Cert & other) const
Equal operator to compare two objects
Referenced by operator!=().
string X509Cert::serial () const
Returns X.509 certificate serial number.
Exceptions
Exception exception is thrown if the serial is incorrect.
string X509Cert::subjectName (const std::string & obj = std::string()) const
Return subject name as string.
Parameters
obj empty string then returns whole issuer name. Otherwise, for example, if set to CN then returns Common name part from issuer name.
Exceptions
Exception exception is throws if the conversion failed.
The documentation for this class was generated from the following files:
X509Cert.h
X509Cert.cpp