libdigidocpp: digidoc::XmlConfV3 Class Reference
digidoc::XmlConfV3 Class Reference
Version 3 of XML Configuration class.
#include <XmlConf.h>
Inherits digidoc::ConfV3.
Public Member Functions
XmlConfV3 (const std::string &path="", const std::string &schema="")
virtual ~XmlConfV3 ()
virtual int logLevel () const
virtual std::string logFile () const
virtual std::string xsdPath () const
virtual std::string PKCS11Driver () const
virtual std::string ocsp (const std::string &issuer) const
virtual DEPRECATED_DIGIDOCPP
std::string certsPath () const
virtual std::string proxyHost () const
virtual std::string proxyPort () const
virtual std::string proxyUser () const
virtual std::string proxyPass () const
virtual std::string PKCS12Cert () const
virtual std::string PKCS12Pass () const
virtual bool PKCS12Disable () const
virtual std::string TSUrl () const
virtual bool TSLAutoUpdate () const
virtual std::string TSLCache () const
virtual DEPRECATED_DIGIDOCPP
X509Cert TSLCert () const
virtual bool TSLOnlineDigest () const
virtual int TSLTimeOut () const
virtual std::string TSLUrl () const
virtual void setProxyHost (const std::string &host)
virtual void setProxyPort (const std::string &port)
virtual void setProxyUser (const std::string &user)
virtual void setProxyPass (const std::string &pass)
virtual void setPKCS12Cert (const std::string &cert)
virtual void setPKCS12Pass (const std::string &pass)
virtual void setPKCS12Disable (bool disable)
virtual void setTSLOnlineDigest (bool enable)
virtual void setTSLTimeOut (int timeOut)
Public Member Functions inherited from digidoc::ConfV3
ConfV3 ()
virtual ~ConfV3 ()
virtual bool TSLAllowExpired () const
virtual std::vector< X509Cert > TSLCerts () const
Public Member Functions inherited from digidoc::ConfV2
ConfV2 ()
virtual ~ConfV2 ()
Public Member Functions inherited from digidoc::Conf
Conf ()
virtual ~Conf ()
virtual std::string digestUri () const
virtual std::string libdigidocConf () const
virtual DEPRECATED_DIGIDOCPP bool bdoc1Supported () const
virtual std::string defaultPolicyId () const
Additional Inherited Members
Static Public Member Functions inherited from digidoc::ConfV3
static ConfV3 * instance ()
Static Public Member Functions inherited from digidoc::ConfV2
static ConfV2 * instance ()
Static Public Member Functions inherited from digidoc::Conf
static void init (Conf *conf)
static Conf * instance ()
Detailed Description
Version 3 of XML Configuration class.
See also
digidoc::ConfV2
Constructor & Destructor Documentation
XmlConfV3::XmlConfV3 (const std::string & path = "", const std::string & schema = "") explicit
Initialize xml conf from path
XmlConfV3::~XmlConfV3 () virtual
Member Function Documentation
virtual DEPRECATED_DIGIDOCPP std::string digidoc::XmlConfV3::certsPath () const virtual
Gets Certificate store location.
Deprecated:
unused
Reimplemented from digidoc::Conf.
virtual std::string digidoc::XmlConfV3::logFile () const virtual
Gets log file location. Default log goes to standard out stream
Reimplemented from digidoc::Conf.
virtual int digidoc::XmlConfV3::logLevel () const virtual
Returns log level. 0 = Error 1 = Warn 2 = Info 3 = Debug
Reimplemented from digidoc::Conf.
string XmlConfV3::ocsp (const std::string & issuer) const virtual
Return OCSP request URL
Parameters
issuer OCSP issuer.
Reimplemented from digidoc::Conf.
References digidoc::Conf::ocsp().
virtual std::string digidoc::XmlConfV3::PKCS11Driver () const virtual
Returns PKCS11 driver file path
Reimplemented from digidoc::Conf.
virtual std::string digidoc::XmlConfV3::PKCS12Cert () const virtual
Gets PKCS12 certificate file location.
Used for signing OCSP request
Reimplemented from digidoc::Conf.
virtual bool digidoc::XmlConfV3::PKCS12Disable () const virtual
Gets PKCS12 usage.
See also
digidoc::Conf::PKCS12Cert
Reimplemented from digidoc::Conf.
virtual std::string digidoc::XmlConfV3::PKCS12Pass () const virtual
Gets PKCS12 password.
See also
digidoc::Conf::PKCS12Cert
Reimplemented from digidoc::Conf.
virtual std::string digidoc::XmlConfV3::proxyHost () const virtual
Gets proxy host address.
Reimplemented from digidoc::Conf.
virtual std::string digidoc::XmlConfV3::proxyPass () const virtual
Gets proxy login password.
Reimplemented from digidoc::Conf.
virtual std::string digidoc::XmlConfV3::proxyPort () const virtual
Gets proxy port number.
Reimplemented from digidoc::Conf.
virtual std::string digidoc::XmlConfV3::proxyUser () const virtual
Gets proxy user name.
Reimplemented from digidoc::Conf.
void digidoc::XmlConfV3::setPKCS12Cert (const std::string & cert) virtual
Sets a PKCS#12 certficate path. Also adds or replaces PKCS#12 certificate path in the user configuration file. By default the PKCS#12 certificate file should be located at default path, given by getUserConfDir() function.
Parameters
cert PKCS#12 certificate location path.
Exceptions
IOException exception is thrown if saving a PKCS#12 certificate path into a user configuration file fails.
void XmlConfV3::setPKCS12Disable (bool disable) virtual
Sets a PKCS#12 certificate usage. Also adds or replaces PKCS#12 certificate usage in the user configuration file.
Parameters
disable PKCS#12 certificate usage.
Exceptions
IOException exception is thrown if saving a PKCS#12 certificate usage into a user configuration file fails.
References digidoc::Conf::PKCS12Disable().
void digidoc::XmlConfV3::setPKCS12Pass (const std::string & pass) virtual
Sets a PKCS#12 certificate password. Also adds or replaces PKCS#12 certificate password in the user configuration file.
Parameters
pass PKCS#12 certificate password.
Exceptions
IOException exception is thrown if saving a PKCS#12 certificate password into a user configuration file fails.
void digidoc::XmlConfV3::setProxyHost (const std::string & host) virtual
Sets a Proxy host address. Also adds or replaces proxy host data in the user configuration file.
Parameters
host proxy host address.
Exceptions
IOException exception is thrown if saving a proxy host address into a user configuration file fails.
void digidoc::XmlConfV3::setProxyPass (const std::string & pass) virtual
Sets a Proxy password. Also adds or replaces proxy password in the user configuration file.
Parameters
pass proxy password.
Exceptions
IOException exception is thrown if saving a proxy password into a user configuration file fails.
void digidoc::XmlConfV3::setProxyPort (const std::string & port) virtual
Sets a Proxy port number. Also adds or replaces proxy port data in the user configuration file.
Parameters
port proxy port number.
Exceptions
IOException exception is thrown if saving a proxy port number into a user configuration file fails.
void digidoc::XmlConfV3::setProxyUser (const std::string & user) virtual
Sets a Proxy user name. Also adds or replaces proxy user name in the user configuration file.
Parameters
user proxy user name.
Exceptions
IOException exception is thrown if saving a proxy user name into a user configuration file fails.
void XmlConfV3::setTSLOnlineDigest (bool enable) virtual
Enables/Disables online digest check
References digidoc::ConfV3::TSLOnlineDigest().
void XmlConfV3::setTSLTimeOut (int timeOut) virtual
Sets TSL connection timeout
Parameters
timeOut Time out in seconds
References digidoc::ConfV3::TSLTimeOut().
virtual bool digidoc::XmlConfV3::TSLAutoUpdate () const virtual
Download new TSL list when it is expired or invalid
Reimplemented from digidoc::ConfV2.
virtual std::string digidoc::XmlConfV3::TSLCache () const virtual
TSL cache path in local file system
Reimplemented from digidoc::ConfV2.
virtual DEPRECATED_DIGIDOCPP X509Cert digidoc::XmlConfV3::TSLCert () const virtual
TSL master list's (LOTL) signing certificate
Deprecated:
digidoc::ConfV3::TSLCerts
Reimplemented from digidoc::ConfV2.
bool XmlConfV3::TSLOnlineDigest () const virtual
Compare local TSL digest with digest published online to check for newer version
Reimplemented from digidoc::ConfV3.
References digidoc::ConfV3::TSLOnlineDigest().
int XmlConfV3::TSLTimeOut () const virtual
Gets TSL downloading connection's current timeout value
Reimplemented from digidoc::ConfV3.
References digidoc::ConfV3::TSLTimeOut().
virtual std::string digidoc::XmlConfV3::TSLUrl () const virtual
TSL master list's (LOTL) URL
Reimplemented from digidoc::ConfV2.
virtual std::string digidoc::XmlConfV3::TSUrl () const virtual
Returns default time-stamp server URL
Reimplemented from digidoc::ConfV2.
virtual std::string digidoc::XmlConfV3::xsdPath () const virtual
Gets XSD schema files path
Reimplemented from digidoc::Conf.
The documentation for this class was generated from the following files:
XmlConf.h
XmlConf.cpp