libdigidocpp: digidoc::Signer Class Reference
digidoc::Signer Class Reference abstract
Signer interface. Provides interface for signing documents.
#include <Signer.h>
Inherited by digidoc::PKCS11Signer, digidoc::PKCS12Signer, and digidoc::WinSigner.
Public Member Functions
virtual ~Signer ()
virtual X509Cert cert () const =0
virtual std::vector< unsigned char > sign (const std::string &method, const std::vector< unsigned char > &digest) const =0
std::string method () const
std::string profile () const
std::string city () const
std::string stateOrProvince () const
std::string postalCode () const
std::string countryName () const
std::vector< std::string > signerRoles () const
void setMethod (const std::string &method)
void setProfile (const std::string &profile)
void setSignatureProductionPlace (const std::string &city, const std::string &stateOrProvince, const std::string &postalCode, const std::string &countryName)
void setSignerRoles (const std::vector< std::string > &signerRoles)
Protected Member Functions
Signer ()
Detailed Description
Signer interface. Provides interface for signing documents.
Digidoc LIB implements PKCS11, PKCS12, Windows Crypto signer class that allows signing with various tokens. Other implementations may provide signing implementation with other public-key cryptography systems.
Constructor & Destructor Documentation
Signer::~Signer () virtual
Destructor
Signer::Signer () protected
Constructor
Member Function Documentation
digidoc::Signer::cert () const pure virtual
Returns signer certificate. Must be reimplemented when subclassing
Referenced by method().
string Signer::city () const
Returns city from signature production place
Referenced by setSignatureProductionPlace().
string Signer::countryName () const
Returns country from signature production place
Referenced by setSignatureProductionPlace().
string Signer::method () const
Gets signature method
References cert(), and digidoc::X509Cert::certificatePolicies().
Referenced by setMethod(), digidoc::PKCS11Signer::setPin(), digidoc::WinSigner::setSelectFirst(), and digidoc::PKCS12Signer::~PKCS12Signer().
string Signer::postalCode () const
Returns postal code from signature production place
Referenced by setSignatureProductionPlace().
string Signer::profile () const
Referenced by setProfile().
void Signer::setMethod (const std::string & method)
Sets signature method
References method().
void Signer::setProfile (const std::string & profile)
References profile().
void Signer::setSignatureProductionPlace (const std::string & city, const std::string & stateOrProvince, const std::string & postalCode, const std::string & countryName)
Sets signature production place according XAdES standard. Note that setting the signature production place is optional.
Parameters
city
stateOrProvince
postalCode
countryName
References city(), countryName(), postalCode(), and stateOrProvince().
void Signer::setSignerRoles (const std::vector< std::string > & signerRoles)
Sets signature roles according XAdES standard. The parameter may contain the signer’s role and optionally the signer’s resolution. Note that only one signer role value (i.e. one <ClaimedRole> XML element) should be used. If the signer role contains both role and resolution then they must be separated with a slash mark, e.g. “role / resolution”.
References signerRoles().
std::vector< unsigned char > digidoc::Signer::sign (const std::string & method, const std::vector< unsigned char > & digest) const pure virtual
Signs message digest. Must be reimplemented when subclassing
Parameters
method digest method to be used
digest digest to sign
Returns
signature signed result
Exceptions
Exception throws exception on error
vector< string > Signer::signerRoles () const
Returns signer roles
Referenced by setSignerRoles().
string Signer::stateOrProvince () const
Returns state from signature production place
Referenced by setSignatureProductionPlace().
The documentation for this class was generated from the following files:
Signer.h
Signer.cpp