libdigidocpp: digidoc::XmlConf Class Reference
digidoc::XmlConf Class Reference
XML Configuration class.
#include <XmlConf.h>
Inherits digidoc::Conf.
Public Member Functions
XmlConf (const std::string &path="", const std::string &schema="")
virtual ~XmlConf ()
virtual int logLevel () const override
virtual std::string logFile () const override
virtual std::string PKCS11Driver () const override
virtual std::string proxyHost () const override
virtual std::string proxyPort () const override
virtual std::string proxyUser () const override
virtual std::string proxyPass () const override
virtual bool proxyForceSSL () const override
virtual bool proxyTunnelSSL () const override
virtual std::string digestUri () const override
virtual std::string signatureDigestUri () const override
virtual std::string ocsp (const std::string &issuer) const override
virtual std::string TSUrl () const override
virtual std::string verifyServiceUri () const override
virtual std::string PKCS12Cert () const override
virtual std::string PKCS12Pass () const override
virtual bool PKCS12Disable () const override
virtual bool TSLAutoUpdate () const override
virtual std::string TSLCache () const override
virtual bool TSLOnlineDigest () const override
virtual int TSLTimeOut () const override
virtual void setProxyHost (const std::string &host)
virtual void setProxyPort (const std::string &port)
virtual void setProxyUser (const std::string &user)
virtual void setProxyPass (const std::string &pass)
virtual void setProxyTunnelSSL (bool enable)
virtual void setPKCS12Cert (const std::string &cert)
virtual void setPKCS12Pass (const std::string &pass)
virtual void setPKCS12Disable (bool disable)
virtual void setTSLOnlineDigest (bool enable)
virtual void setTSLTimeOut (int timeOut)
Public Member Functions inherited from digidoc::Conf
Conf ()
virtual ~Conf ()
virtual DEPRECATED_DIGIDOCPP std::string libdigidocConf () const
virtual DEPRECATED_DIGIDOCPP std::string certsPath () const
virtual std::string xsdPath () const
virtual bool TSLAllowExpired () const
virtual std::vector< X509Cert > TSLCerts () const
virtual std::string TSLUrl () const
Additional Inherited Members
Static Public Member Functions inherited from digidoc::Conf
static void init (Conf *conf)
static Conf * instance ()
Detailed Description
XML Configuration class.
See also
digidoc::Conf
Constructor & Destructor Documentation
XmlConf::XmlConf (const std::string & path = "", const std::string & schema = "") explicit
XmlConf::~XmlConf () virtual
References digestUri(), logFile(), logLevel(), PKCS11Driver(), PKCS12Cert(), PKCS12Disable(), PKCS12Pass(), proxyForceSSL(), proxyHost(), proxyPass(), proxyPort(), proxyTunnelSSL(), proxyUser(), signatureDigestUri(), TSLAutoUpdate(), TSLCache(), TSLOnlineDigest(), TSLTimeOut(), TSUrl(), and verifyServiceUri().
Member Function Documentation
virtual std::string digidoc::XmlConf::digestUri () const override virtual
Return default digest type as URI
Reimplemented from digidoc::Conf.
Referenced by ~XmlConf().
virtual std::string digidoc::XmlConf::logFile () const override virtual
Gets log file location. Default log goes to standard out stream
Reimplemented from digidoc::Conf.
Referenced by ~XmlConf().
virtual int digidoc::XmlConf::logLevel () const override virtual
Returns log level. 0 = Error 1 = Warn 2 = Info 3 = Debug
Reimplemented from digidoc::Conf.
Referenced by ~XmlConf().
string XmlConf::ocsp (const std::string & issuer) const override virtual
Return OCSP request URL
Parameters
issuer OCSP issuer.
Reimplemented from digidoc::Conf.
References digidoc::Conf::ocsp(), PKCS12Cert(), PKCS12Disable(), PKCS12Pass(), proxyHost(), proxyPass(), proxyPort(), proxyUser(), setPKCS12Cert(), setPKCS12Disable(), setPKCS12Pass(), setProxyHost(), setProxyPass(), setProxyPort(), setProxyUser(), setTSLOnlineDigest(), setTSLTimeOut(), TSLOnlineDigest(), and TSLTimeOut().
virtual std::string digidoc::XmlConf::PKCS11Driver () const override virtual
Returns PKCS11 driver file path
Reimplemented from digidoc::Conf.
Referenced by ~XmlConf().
virtual std::string digidoc::XmlConf::PKCS12Cert () const override virtual
Gets PKCS12 certificate file location.
Used for signing OCSP request
Reimplemented from digidoc::Conf.
Referenced by ocsp(), and ~XmlConf().
virtual bool digidoc::XmlConf::PKCS12Disable () const override virtual
Gets PKCS12 usage.
See also
digidoc::Conf::PKCS12Cert
Reimplemented from digidoc::Conf.
Referenced by ocsp(), and ~XmlConf().
virtual std::string digidoc::XmlConf::PKCS12Pass () const override virtual
Gets PKCS12 password.
See also
digidoc::Conf::PKCS12Cert
Reimplemented from digidoc::Conf.
Referenced by ocsp(), and ~XmlConf().
virtual bool digidoc::XmlConf::proxyForceSSL () const override virtual
Redirect SSL traffic over proxy server Default: false
Reimplemented from digidoc::Conf.
Referenced by ~XmlConf().
virtual std::string digidoc::XmlConf::proxyHost () const override virtual
Gets proxy host address.
Reimplemented from digidoc::Conf.
Referenced by ocsp(), and ~XmlConf().
virtual std::string digidoc::XmlConf::proxyPass () const override virtual
Gets proxy login password.
Reimplemented from digidoc::Conf.
Referenced by ocsp(), and ~XmlConf().
virtual std::string digidoc::XmlConf::proxyPort () const override virtual
Gets proxy port number.
Reimplemented from digidoc::Conf.
Referenced by ocsp(), and ~XmlConf().
virtual bool digidoc::XmlConf::proxyTunnelSSL () const override virtual
Tunnel SSL traffic over proxy server Default: false
Reimplemented from digidoc::Conf.
Referenced by ~XmlConf().
virtual std::string digidoc::XmlConf::proxyUser () const override virtual
Gets proxy user name.
Reimplemented from digidoc::Conf.
Referenced by ocsp(), and ~XmlConf().
void digidoc::XmlConf::setPKCS12Cert (const std::string & cert) virtual
Sets a PKCS#12 certficate path. Also adds or replaces PKCS#12 certificate path in the user configuration file. By default the PKCS#12 certificate file should be located at default path, given by getUserConfDir() function.
Parameters
cert PKCS#12 certificate location path.
Exceptions
Exception exception is thrown if saving a PKCS#12 certificate path into a user configuration file fails.
Referenced by ocsp().
void digidoc::XmlConf::setPKCS12Disable (bool disable) virtual
Sets a PKCS#12 certificate usage. Also adds or replaces PKCS#12 certificate usage in the user configuration file.
Parameters
disable PKCS#12 certificate usage.
Exceptions
Exception exception is thrown if saving a PKCS#12 certificate usage into a user configuration file fails.
Referenced by ocsp().
void digidoc::XmlConf::setPKCS12Pass (const std::string & pass) virtual
Sets a PKCS#12 certificate password. Also adds or replaces PKCS#12 certificate password in the user configuration file.
Parameters
pass PKCS#12 certificate password.
Exceptions
Exception exception is thrown if saving a PKCS#12 certificate password into a user configuration file fails.
Referenced by ocsp().
void digidoc::XmlConf::setProxyHost (const std::string & host) virtual
Sets a Proxy host address. Also adds or replaces proxy host data in the user configuration file.
Parameters
host proxy host address.
Exceptions
Exception exception is thrown if saving a proxy host address into a user configuration file fails.
Referenced by ocsp().
void digidoc::XmlConf::setProxyPass (const std::string & pass) virtual
Sets a Proxy password. Also adds or replaces proxy password in the user configuration file.
Parameters
pass proxy password.
Exceptions
Exception exception is thrown if saving a proxy password into a user configuration file fails.
Referenced by ocsp().
void digidoc::XmlConf::setProxyPort (const std::string & port) virtual
Sets a Proxy port number. Also adds or replaces proxy port data in the user configuration file.
Parameters
port proxy port number.
Exceptions
Exception exception is thrown if saving a proxy port number into a user configuration file fails.
Referenced by ocsp().
void XmlConf::setProxyTunnelSSL (bool enable) virtual
Enables SSL proxy connections
Exceptions
Exception exception is thrown if saving into a user configuration file fails.
References digidoc::Conf::proxyTunnelSSL().
void digidoc::XmlConf::setProxyUser (const std::string & user) virtual
Sets a Proxy user name. Also adds or replaces proxy user name in the user configuration file.
Parameters
user proxy user name.
Exceptions
Exception exception is thrown if saving a proxy user name into a user configuration file fails.
Referenced by ocsp().
void digidoc::XmlConf::setTSLOnlineDigest (bool enable) virtual
Enables/Disables online digest check
Exceptions
Exception exception is thrown if saving a TSL online digest into a user configuration file fails.
Referenced by ocsp().
void digidoc::XmlConf::setTSLTimeOut (int timeOut) virtual
Sets TSL connection timeout
Parameters
timeOut Time out in seconds
Exceptions
Exception exception is thrown if saving a TSL timeout into a user configuration file fails.
Referenced by ocsp().
virtual std::string digidoc::XmlConf::signatureDigestUri () const override virtual
Gets signature digest URI
Reimplemented from digidoc::Conf.
Referenced by ~XmlConf().
virtual bool digidoc::XmlConf::TSLAutoUpdate () const override virtual
Download new TSL list when it is expired or invalid
Reimplemented from digidoc::Conf.
Referenced by ~XmlConf().
virtual std::string digidoc::XmlConf::TSLCache () const override virtual
TSL cache path in local file system
Reimplemented from digidoc::Conf.
Referenced by ~XmlConf().
virtual bool digidoc::XmlConf::TSLOnlineDigest () const override virtual
Compare local TSL digest with digest published online to check for newer version
Reimplemented from digidoc::Conf.
Referenced by ocsp(), and ~XmlConf().
virtual int digidoc::XmlConf::TSLTimeOut () const override virtual
Gets TSL downloading connection's current timeout value
Reimplemented from digidoc::Conf.
Referenced by ocsp(), and ~XmlConf().
virtual std::string digidoc::XmlConf::TSUrl () const override virtual
Returns default time-stamp server URL
Reimplemented from digidoc::Conf.
Referenced by ~XmlConf().
virtual std::string digidoc::XmlConf::verifyServiceUri () const override virtual
Gets verify service URI
Reimplemented from digidoc::Conf.
Referenced by ~XmlConf().
The documentation for this class was generated from the following files:
XmlConf.h
XmlConf.cpp