libdigidocpp: digidoc::ConfV3 Class Reference
digidoc::ConfV3 Class Reference
Verison 3 of configuration class to add additonial parameters.
#include <Conf.h>
Inherits digidoc::ConfV2.
Inherited by digidoc::XmlConfV3.
Public Member Functions
ConfV3 ()
virtual ~ConfV3 ()
virtual bool TSLAllowExpired () const
virtual std::vector< X509Cert > TSLCerts () const
virtual bool TSLOnlineDigest () const
virtual int TSLTimeOut () const
Public Member Functions inherited from digidoc::ConfV2
ConfV2 ()
virtual ~ConfV2 ()
virtual std::string TSUrl () const
virtual bool TSLAutoUpdate () const
virtual std::string TSLCache () const
virtual DEPRECATED_DIGIDOCPP
X509Cert TSLCert () const
virtual std::string TSLUrl () const
Public Member Functions inherited from digidoc::Conf
Conf ()
virtual ~Conf ()
virtual int logLevel () const
virtual std::string logFile () const
virtual std::string digestUri () const
virtual std::string xsdPath () const
virtual std::string PKCS11Driver () const
virtual std::string ocsp (const std::string &issuer) const
virtual DEPRECATED_DIGIDOCPP
std::string certsPath () const
virtual std::string proxyHost () const
virtual std::string proxyPort () const
virtual std::string proxyUser () const
virtual std::string proxyPass () const
virtual std::string PKCS12Cert () const
virtual std::string PKCS12Pass () const
virtual bool PKCS12Disable () const
virtual std::string libdigidocConf () const
virtual DEPRECATED_DIGIDOCPP bool bdoc1Supported () const
virtual std::string defaultPolicyId () const
Static Public Member Functions
static ConfV3 * instance ()
Static Public Member Functions inherited from digidoc::ConfV2
static ConfV2 * instance ()
Static Public Member Functions inherited from digidoc::Conf
static void init (Conf *conf)
static Conf * instance ()
Detailed Description
Verison 3 of configuration class to add additonial parameters.
See also
digidoc::ConfV2
Configuration parameters
Constructor & Destructor Documentation
ConfV3::ConfV3 ()
Version 3 config with new parameters
ConfV3::~ConfV3 () virtual
Member Function Documentation
ConfV3 * ConfV3::instance () static
Return global instance object
References digidoc::Conf::instance().
bool ConfV3::TSLAllowExpired () const virtual
Allow expired TSL lists
vector< X509Cert > ConfV3::TSLCerts () const virtual
TSL master list's (LOTL) signing certificates
References digidoc::X509Cert::Pem.
bool ConfV3::TSLOnlineDigest () const virtual
Compare local TSL digest with digest published online to check for newer version
Reimplemented in digidoc::XmlConfV3.
Referenced by digidoc::XmlConfV3::setTSLOnlineDigest(), and digidoc::XmlConfV3::TSLOnlineDigest().
int ConfV3::TSLTimeOut () const virtual
Gets TSL downloading connection's current timeout value
Reimplemented in digidoc::XmlConfV3.
Referenced by digidoc::XmlConfV3::setTSLTimeOut(), and digidoc::XmlConfV3::TSLTimeOut().
The documentation for this class was generated from the following files:
Conf.h
Conf.cpp