libdigidocpp: digidoc::Container Class Reference
digidoc::Container Class Reference
Offers functionality for handling data files and signatures in a container.
#include <Container.h>
Public Types
enum DocumentType { AsicType, BDocType, DDocType }
Public Member Functions
Container (DocumentType type=AsicType)
Container (const std::string &path)
~Container ()
void save (const std::string &path="")
std::string mediaType () const
void addDataFile (const std::string &path, const std::string &mediaType)
void addDataFile (std::istream *is, const std::string &fileName, const std::string &mediaType)
DataFileList dataFiles () const
void removeDataFile (unsigned int id)
void addRawSignature (const std::vector< unsigned char > &signature)
void addRawSignature (std::istream &signature)
SignatureList signatures () const
void removeSignature (unsigned int id)
Signature * sign (Signer *signer)
Signature * sign (Signer *signer, const std::string &profile)
Signature * sign (const std::string &city, const std::string &stateOrProvince, const std::string &postalCode, const std::string &countryName, const std::vector< std::string > &signerRoles, const std::string &pin, bool useFirstCertificate=true)
Detailed Description
Offers functionality for handling data files and signatures in a container.
Container can contain several files and all these files can be signed using signing certificates. Container can only be signed if it contains data files. data files can be added and removed from container only if the container is not signed. To add or remove data files from signed container remove all the signatures before modifying data files list in container.
Member Enumeration Documentation
enum digidoc::Container::DocumentType
Enum to select container type to create
Enumerator
AsicType
creates new BDOC 2.1 container with mime-type "application/vnd.etsi.asic-e+zip". See also Format of digitally signed file
BDocType
creates new BDOC 1.0 container with mime-type "application/vnd.bdoc-1.0"
Deprecated:
Defauts to digidoc::Container::AsicType
Note
the functionality of creating new files in DigiDoc file formats BDOC 1.0 is not supported.
DDocType
creates new DIGIDOC-XML 1.3 container. Note that using BDOC 2.1 format is preferred for new documents. Support for DIGIDOC-XML 1.3 format has been added to Libdigidocpp via CDigiDoc library. Note that usage of this document format is tested only indirectly via DigiDoc3 Client desktop application which uses CDigiDoc as a base layer.
Note
the functionality of creating new files in DigiDoc file formats SK-XML, DIGIDOC-XML 1.1, DIGIDOC-XML 1.2 is not supported.
Constructor & Destructor Documentation
Container::Container (DocumentType type = AsicType)
Create a new container object and specify the DigiDoc container type
References DDocType.
Container::Container (const std::string & path)
Opens container from a file
Parameters
path
Exceptions
Exception
Container::~Container ()
Releases resources.
Member Function Documentation
void Container::addDataFile (const std::string & path, const std::string & mediaType)
Adds data file from file system to the container.
Parameters
path a data file, which is added to the container.
mediaType MIME type of the data file, for example “text/plain” or “application/msword”
Exceptions
Exception exception is thrown if the data file path is incorrect or a data file with same file name already exists. Also, no data file can be added if the container already has one or more signatures.
Note
Data files can be removed from container only after all signatures are removed.
void Container::addDataFile (std::istream * is, const std::string & fileName, const std::string & mediaType)
Adds the data from an input stream (i.e. the data file contents can be read from internal memory buffer)
Parameters
is input stream from where data is read
fileName data file name in the container
mediaType MIME type of the data file, for example “text/plain” or “application/msword”
Exceptions
Exception exception is thrown if the data file path is incorrect or a data file with same file name already exists. Also, no data file can be added if the container already has one or more signatures.
Note
Data files can be removed from container only after all signatures are removed.
void Container::addRawSignature (const std::vector< unsigned char > & signature)
Adds signature to the container.
Parameters
signature signature, which is added to the container.
Exceptions
Exception throws exception if there are no data files in container.
void Container::addRawSignature (std::istream & signature)
Adds signature to the container.
Parameters
signature signature, which is added to the container.
Exceptions
Exception throws exception if there are no data files in container.
DataFileList Container::dataFiles () const
List of all the data files in the container
string Container::mediaType () const
Returns current data file format
void Container::removeDataFile (unsigned int id)
Removes data file from container by data file id. Data files can be removed from container only after all signatures are removed.
Parameters
id data file's id, which will be removed.
Exceptions
Exception throws exception if the data file id is incorrect or there are one or more signatures.
void Container::removeSignature (unsigned int id)
Removes signature from container by signature id.
Parameters
id signature's id, which will be removed.
Exceptions
Exception throws exception if the signature id is incorrect.
void Container::save (const std::string & path = "")
Saves the container.
Exceptions
Exception is thrown if there was a failure saving BDOC container. For example added data file does not exist.
Signature * Container::sign (Signer * signer)
Signs all data files in container.
Parameters
signer signer implementation.
Exceptions
Exception exception is thrown if signing the container failed.
Referenced by sign().
Signature * Container::sign (Signer * signer, const std::string & profile)
Signs all data files in container.
Parameters
signer signer implementation.
profile type enables to specify the signature profile. Defaults to BDOC profile with time-stamp. To create BDOC with time-mark, set the parameter value to "time-mark". See also Supported functional properties.
Exceptions
Exception exception is thrown if signing the container failed.
Signature * Container::sign (const std::string & city, const std::string & stateOrProvince, const std::string & postalCode, const std::string & countryName, const std::vector< std::string > & signerRoles, const std::string & pin, bool useFirstCertificate = true)
Signs all data files in container.
Parameters
city sets a signature production place signed property (optional)
stateOrProvince sets a signature production place signed property (optional)
postalCode sets a signature production place signed property (optional)
countryName sets a signature production place signed property (optional)
signerRoles the parameter may contain the signer’s role and optionally the signer’s resolution. Note that only one signer role value (i.e. one <ClaimedRole> XML element) should be used. If the signer role contains both role and resolution then they must be separated with a slash mark, e.g. “role / resolution”. Note that when setting the resolution value then role must also be specified.
pin PIN code for accessing the private key
useFirstCertificate if set to “true”, determines that the first signing certificate that is found from the certificate store is chosen for signature creation and the certificate selection’s dialog window is not displayed to the user
References digidoc::PKCS11Signer::setPin(), digidoc::Signer::setSignatureProductionPlace(), digidoc::Signer::setSignerRoles(), and sign().
SignatureList Container::signatures () const
Returnes list of all container's signatures.
The documentation for this class was generated from the following files:
Container.h
Container.cpp