libdigidocpp: digidoc::ConfV4 Class Reference
digidoc::ConfV4 Class Reference
Verison 4 of configuration class to add additonial parameters.
#include <Conf.h>
Inherits digidoc::ConfV3.
Inherited by digidoc::XmlConfV4.
Public Member Functions
ConfV4 ()
virtual ~ConfV4 ()
virtual bool proxyForceSSL () const
virtual bool proxyTunnelSSL () const
virtual std::string signatureDigestUri () const
Public Member Functions inherited from digidoc::ConfV3
ConfV3 ()
virtual ~ConfV3 ()
virtual bool TSLAllowExpired () const
virtual std::vector< X509Cert > TSLCerts () const
virtual bool TSLOnlineDigest () const
virtual int TSLTimeOut () const
Public Member Functions inherited from digidoc::ConfV2
ConfV2 ()
virtual ~ConfV2 ()
virtual std::string TSUrl () const
virtual bool TSLAutoUpdate () const
virtual std::string TSLCache () const
virtual DEPRECATED_DIGIDOCPP X509Cert TSLCert () const
virtual std::string TSLUrl () const
Public Member Functions inherited from digidoc::Conf
Conf ()
virtual ~Conf ()
virtual int logLevel () const
virtual std::string logFile () const
virtual std::string digestUri () const
virtual std::string xsdPath () const
virtual std::string PKCS11Driver () const
virtual std::string ocsp (const std::string &issuer) const
virtual DEPRECATED_DIGIDOCPP std::string certsPath () const
virtual std::string proxyHost () const
virtual std::string proxyPort () const
virtual std::string proxyUser () const
virtual std::string proxyPass () const
virtual std::string PKCS12Cert () const
virtual std::string PKCS12Pass () const
virtual bool PKCS12Disable () const
virtual std::string libdigidocConf () const
virtual DEPRECATED_DIGIDOCPP bool bdoc1Supported () const
virtual std::string defaultPolicyId () const
Static Public Member Functions
static ConfV4 * instance ()
Static Public Member Functions inherited from digidoc::ConfV3
static ConfV3 * instance ()
Static Public Member Functions inherited from digidoc::ConfV2
static ConfV2 * instance ()
Static Public Member Functions inherited from digidoc::Conf
static void init (Conf *conf)
static Conf * instance ()
Detailed Description
Verison 4 of configuration class to add additonial parameters.
See also
digidoc::ConfV3
Configuration parameters
Constructor & Destructor Documentation
ConfV4::ConfV4 ()
Version 4 config with new parameters
ConfV4::~ConfV4 () virtual
Member Function Documentation
ConfV4 * ConfV4::instance () static
Return global instance object
References digidoc::Conf::instance().
bool ConfV4::proxyForceSSL () const virtual
Redirect SSL traffic over proxy server Default: false
Reimplemented in digidoc::XmlConfV4.
Referenced by digidoc::XmlConfV4::proxyForceSSL().
bool ConfV4::proxyTunnelSSL () const virtual
Tunnel SSL traffic over proxy server Default: false
Reimplemented in digidoc::XmlConfV4.
Referenced by digidoc::XmlConfV4::proxyTunnelSSL().
string ConfV4::signatureDigestUri () const virtual
Gets signature digest URI
Reimplemented in digidoc::XmlConfV4.
Referenced by digidoc::XmlConfV4::signatureDigestUri().
The documentation for this class was generated from the following files:
Conf.h
Conf.cpp