libdigidocpp: digidoc Namespace Reference
digidoc Namespace Reference
Classes
class Conf
Configuration class which can reimplemented and virtual methods overloaded.
class ConfV2
Verison 2 of configuration class to add additonial parameters.
class ConfV3
Verison 3 of configuration class to add additonial parameters.
class ConfV4
Verison 4 of configuration class to add additonial parameters.
class Container
Offers functionality for handling data files and signatures in a container.
class DataFile
Data file wrapper providing methods for handling signed files or files to be signed in Container.
class Exception
Base exception class of the digidoc implementation.
class PKCS11Signer
Implements Signer interface for ID-Cards, which support PKCS#11 protocol.
class Signature
Signature interface. Provides interface for handling a signature and the corresponding OCSP response properties.
class Signer
Signer interface. Provides interface for signing documents.
class X509Cert
Wrapper for OpenSSL X509 certificate structure.
class XmlConf
XML Configuration class.
class XmlConfV2
Version 2 of XML Configuration class.
class XmlConfV3
Version 3 of XML Configuration class.
class XmlConfV4
Version 4 of XML Configuration class.
Typedefs
typedef std::vector< DataFile > DataFileList
typedef std::vector< Signature * > SignatureList
typedef void(* initCallBack) (const Exception *e)
Functions
EXP_DIGIDOC std::string appInfo ()
EXP_DIGIDOC void initialize (const std::string &appInfo="libdigidocpp")
EXP_DIGIDOC void initializeEx (const std::string &appInfo="libdigidocpp", initCallBack callBack=nullptr)
EXP_DIGIDOC void terminate ()
EXP_DIGIDOC std::string version ()
Typedef Documentation
typedef std::vector<DataFile> digidoc::DataFileList
typedef void(* digidoc::initCallBack) (const Exception *e)
typedef std::vector<Signature*> digidoc::SignatureList
Function Documentation
string digidoc::appInfo ()
Returns registered application name
Referenced by initializeEx().
void digidoc::initialize (const std::string & appInfo = "libdigidocpp")
Libdigidocpp’s initialization method: initializes dependent libraries, loads configuration settings from default configuration files (see Configuring Libdigidocpp) and initializes certificate store using TSL lists
Parameters
appInfo Application name for user agent string
References initializeEx().
void digidoc::initializeEx (const std::string & appInfo = "libdigidocpp", initCallBack callBack = nullptr)
Libdigidocpp’s initialization method: initializes dependent libraries, loads configuration settings from default configuration files (see Configuring Libdigidocpp) and initializes certificate store using TSL lists
Parameters
appInfo Application name for user agent string
callBack Callback when background thread TSL loading is completed
References appInfo(), digidoc::Conf::init(), and digidoc::Conf::instance().
Referenced by initialize().
void digidoc::terminate ()
The termination method closes libraries used in Libdigidocpp implementation and deletes temporary files that may have been written to disk when working with the library.
References digidoc::Conf::init().
string digidoc::version ()
Returns libdigidocpp library version