libdigidocpp: digidoc::Conf Class Reference
digidoc::Conf Class Reference
Configuration class which can reimplemented and virtual methods overloaded.
#include <Conf.h>
Inherited by digidoc::XmlConf.
Public Member Functions
Conf ()
virtual ~Conf ()
virtual int logLevel () const
virtual std::string logFile () const
virtual DEPRECATED_DIGIDOCPP std::string libdigidocConf () const
virtual DEPRECATED_DIGIDOCPP std::string certsPath () const
virtual std::string xsdPath () const
virtual std::string PKCS11Driver () const
virtual std::string proxyHost () const
virtual std::string proxyPort () const
virtual std::string proxyUser () const
virtual std::string proxyPass () const
virtual bool proxyForceSSL () const
virtual bool proxyTunnelSSL () const
virtual std::string digestUri () const
virtual std::string signatureDigestUri () const
virtual std::string ocsp (const std::string &issuer) const
virtual std::string TSUrl () const
virtual std::string PKCS12Cert () const
virtual std::string PKCS12Pass () const
virtual bool PKCS12Disable () const
virtual bool TSLAllowExpired () const
virtual bool TSLAutoUpdate () const
virtual std::string TSLCache () const
virtual std::vector< X509Cert > TSLCerts () const
virtual bool TSLOnlineDigest () const
virtual int TSLTimeOut () const
virtual std::string TSLUrl () const
Static Public Member Functions
static void init (Conf *conf)
static Conf * instance ()
Detailed Description
Configuration class which can reimplemented and virtual methods overloaded.
See also
Configuration parameters
Constructor & Destructor Documentation
Conf::Conf ()
Configuration parameters
Conf::~Conf () virtual
Member Function Documentation
string Conf::certsPath () const virtual
Gets Certificate store location.
Deprecated:
unused
string Conf::digestUri () const virtual
Return default digest type as URI
Reimplemented in digidoc::XmlConf.
void Conf::init (Conf * conf) static
Init global Conf with conf
Referenced by digidoc::initialize(), and digidoc::terminate().
Conf * Conf::instance () static
Return global instance object
Referenced by digidoc::initialize(), and digidoc::PKCS11Signer::PKCS11Signer().
string Conf::libdigidocConf () const virtual
Returns libdigidoc library configuration file's (digidoc.ini) file location
string Conf::logFile () const virtual
Gets log file location. Default log goes to standard out stream
Reimplemented in digidoc::XmlConf.
int Conf::logLevel () const virtual
Returns log level. 0 = Error 1 = Warn 2 = Info 3 = Debug
Reimplemented in digidoc::XmlConf.
string Conf::ocsp (const std::string & issuer) const virtual
Return OCSP request URL
Parameters
issuer OCSP issuer.
Reimplemented in digidoc::XmlConf.
Referenced by digidoc::XmlConf::ocsp().
string Conf::PKCS11Driver () const virtual
Returns PKCS11 driver file path
Reimplemented in digidoc::XmlConf.
Referenced by digidoc::PKCS11Signer::PKCS11Signer().
string Conf::PKCS12Cert () const virtual
Gets PKCS12 certificate file location.
Used for signing OCSP request
Reimplemented in digidoc::XmlConf.
bool Conf::PKCS12Disable () const virtual
Gets PKCS12 usage.
See also
digidoc::Conf::PKCS12Cert
Reimplemented in digidoc::XmlConf.
string Conf::PKCS12Pass () const virtual
Gets PKCS12 password.
See also
digidoc::Conf::PKCS12Cert
Reimplemented in digidoc::XmlConf.
bool Conf::proxyForceSSL () const virtual
Redirect SSL traffic over proxy server Default: false
Reimplemented in digidoc::XmlConf.
string Conf::proxyHost () const virtual
Gets proxy host address.
Reimplemented in digidoc::XmlConf.
string Conf::proxyPass () const virtual
Gets proxy login password.
Reimplemented in digidoc::XmlConf.
string Conf::proxyPort () const virtual
Gets proxy port number.
Reimplemented in digidoc::XmlConf.
bool Conf::proxyTunnelSSL () const virtual
Tunnel SSL traffic over proxy server Default: false
Reimplemented in digidoc::XmlConf.
Referenced by digidoc::XmlConf::setProxyTunnelSSL().
string Conf::proxyUser () const virtual
Gets proxy user name.
Reimplemented in digidoc::XmlConf.
string Conf::signatureDigestUri () const virtual
Gets signature digest URI
Reimplemented in digidoc::XmlConf.
bool Conf::TSLAllowExpired () const virtual
Allow expired TSL lists
bool Conf::TSLAutoUpdate () const virtual
Download new TSL list when it is expired or invalid
Reimplemented in digidoc::XmlConf.
string Conf::TSLCache () const virtual
TSL cache path in local file system
Reimplemented in digidoc::XmlConf.
vector< X509Cert > Conf::TSLCerts () const virtual
TSL master list's (LOTL) signing certificates
References digidoc::X509Cert::Pem.
bool Conf::TSLOnlineDigest () const virtual
Compare local TSL digest with digest published online to check for newer version
Reimplemented in digidoc::XmlConf.
int Conf::TSLTimeOut () const virtual
Gets TSL downloading connection's current timeout value
Reimplemented in digidoc::XmlConf.
string Conf::TSLUrl () const virtual
TSL master list's (LOTL) URL
string Conf::TSUrl () const virtual
Returns default time-stamp server URL
Reimplemented in digidoc::XmlConf.
string Conf::xsdPath () const virtual
Gets XSD schema files path
The documentation for this class was generated from the following files:
Conf.h
Conf.cpp