libdigidocpp: digidoc::Exception Class Reference
digidoc::Exception Class Reference
Base exception class of the digidoc implementation.
#include <Exception.h>
Public Types
enum ExceptionCode {
General = 0, CertificateIssuerMissing = 10, CertificateRevoked = 5, CertificateUnknown = 6,
OCSPResponderMissing = 8, OCSPCertMissing = 9, OCSPTimeSlot = 7, OCSPRequestUnauthorized = 11,
PINCanceled = 2, PINFailed = 4, PINIncorrect = 1, PINLocked = 3,
ReferenceDigestWeak = 12, SignatureDigestWeak = 13, DataFileNameSpaceWarning = 14, IssuerNameSpaceWarning = 15,
ProducedATLateWarning = 16, DDocError = 512
}
typedef std::vector< Exception > Causes
Public Member Functions
Exception (const std::string &file, int line, const std::string &msg)
Exception (const std::string &file, int line, const std::string &msg, const Exception &cause)
virtual ~Exception ()
std::string file () const
int line () const
ExceptionCode code () const
std::string msg () const
Causes causes () const
void addCause (const Exception &cause)
void setCode (ExceptionCode Code)
Static Public Member Functions
static void addWarningIgnore (ExceptionCode code)
static void setWarningIgnoreList (const std::vector< ExceptionCode > &list)
static bool hasWarningIgnore (ExceptionCode code)
Detailed Description
Base exception class of the digidoc implementation.
Member Typedef Documentation
typedef std::vector<Exception> digidoc::Exception::Causes
Member Enumeration Documentation
enum digidoc::Exception::ExceptionCode
Exception code
Enumerator
General
General error, no specific code
CertificateIssuerMissing
Signer's certificate's issuer certificate is missing
CertificateRevoked
Certificate status is revoked in OCSP response
CertificateUnknown
Certificate status is unknown in OCSP response
OCSPResponderMissing
OCSP Responder is missing
OCSPCertMissing
OCSP Responder certificate is missing
OCSPTimeSlot
OCSP Response is not in valid time slot
OCSPRequestUnauthorized
OCSP Responder requires the OCSP request to be signed
PINCanceled
PIN cancelled exception
PINFailed
PIN verification error
PINIncorrect
PIN incorrect error
PINLocked
PIN locked error
ReferenceDigestWeak
One or more referenced objects in BDoc container are calculated by using weaker digest method that recommended
SignatureDigestWeak
The digest that is signed in BDoc container has been calculated by using weaker digest method than recommended
DataFileNameSpaceWarning
DDoc warning: <DataFile> XML element is missing xmlns attribute
IssuerNameSpaceWarning
DDoc warning: <X509IssuerName> and/or <X509IssuerSerial> XML element is missing xmlns attribute
ProducedATLateWarning
TimeStamp and OCSP time difference is more than 15 minutes
DDocError
DDoc libdigidoc error codes bit masked
Constructor & Destructor Documentation
Exception::Exception (const std::string & file, int line, const std::string & msg)
Parameters
file source file name, where the exception was thrown.
line line of the file, where the exception was thrown.
msg error message.
Exception::Exception (const std::string & file, int line, const std::string & msg, const Exception & cause)
Convenience constructor when there is just one cause for this Exception.
Parameters
file source file name, where the exception was thrown.
line line of the file, where the exception was thrown.
msg error message.
cause cause of the exception.
See also
causes()
References addCause().
Exception::~Exception () virtual
Releases memory
Member Function Documentation
void Exception::addCause (const Exception & cause)
Adds child Exception
Referenced by Exception().
void Exception::addWarningIgnore (ExceptionCode code) static
Ignore Warning exceptions globaly
Parameters
code Push additional exception to list
Exception::Causes Exception::causes () const
Returns exception causes (other exceptions that caused this exception).
Exception::ExceptionCode Exception::code () const
Returns exception code
Referenced by hasWarningIgnore(), and setCode().
string Exception::file () const
Returns exception file
bool Exception::hasWarningIgnore (ExceptionCode code) static
Verifies if Warning exception is in igonre list
References code().
int Exception::line () const
Returns exception line
string Exception::msg () const
Returns error message.
void Exception::setCode (ExceptionCode code)
Sets exception code
References code().
void Exception::setWarningIgnoreList (const std::vector< ExceptionCode > & list) static
Ignore Warning exceptions globaly
Parameters
list Set new exception list
The documentation for this class was generated from the following files:
Exception.h
Exception.cpp